import { PageContent } from './types';

export const homeContent: PageContent = {
  metadata: {
    title: 'Chale Institute - Empowering Education and Innovation',
    description: 'Welcome to Chale Institute, where we empower students through innovative education programs and cutting-edge research opportunities.',
    keywords: ['education', 'innovation', 'research', 'learning', 'institute'],
    ogImage: '/images/og-image.jpg',
  },
  hero: {
    title: 'Local Ideas, Global Freedom.',
    subtitle: 'We develop a new generation of thought leaders who translate indigenous African Ideas of Liberty into bold policies for a modern, prosperous, and free continent.',
    backgroundImage: '/images/hero-bg.jpg',
    cta: {
      title: '',
      primaryButton: {
        label: 'Sign up Now',
        href: '#programs',
      },
    },
  },
  sections: [
    {
      id: 'showcase',
      type: 'projects',
      title: 'See Our Work',
      description: 'Explore our impactful projects and initiatives that are making a difference',
      data: {
        projects: [
          {
            id: 'project-1',
            title: 'Advocates of Liberty Fellowship',
            description: 'Training the next generation of African thought leaders requires time and commitment from aspiring leaders as well as from the trainers. Our fellowship includes design thinking, global citizenship education, Classical African philosophy and a new value system that prioritises the rights of every individual in the society. All of these and more, we have put together in our Advocates of Liberty Fellowship.',
            image: '/images/project-liberty.jpg',
            href: '/projects/liberty-fellowship',
            category: 'Fellowship',
          },
          {
            id: 'project-2',
            title: 'Google Explore ML Program',
            description: 'Training AI Models and exploring machine learning technologies to empower students with cutting-edge skills for the future of technology and innovation.',
            image: '/images/project-google-ml.jpg',
            href: '/projects/google-ml',
            category: 'Technology',
          },
          {
            id: 'project-3',
            title: 'Youth Entrepreneurship Initiative',
            description: 'Empowering young entrepreneurs with the skills, resources, and mentorship needed to build sustainable businesses and create positive social impact in their communities.',
            image: '/images/project-entrepreneurship.jpg',
            href: '/projects/entrepreneurship',
            category: 'Business',
          },
          {
            id: 'project-4',
            title: 'Sustainable Development Research',
            description: 'Conducting groundbreaking research on sustainable development practices, renewable energy solutions, and environmental conservation strategies for a better tomorrow.',
            image: '/images/project-sustainability.jpg',
            href: '/projects/sustainability',
            category: 'Research',
          },
        ],
      },
    },
    {
      id: 'publications',
      type: 'publications',
      title: 'Our Publications',
      description: 'Explore our research papers, reports, and thought leadership publications',
      data: {
        publications: [
          {
            id: 'pub-1',
            image: '/images/publication-life-expectancy.jpg',
            title: 'The life expectancy crisis in Nigeria - A Public Health Report',
            description: 'A CIDS Position paper on Nigeria\'s latest ranking as the country with the lowest life expectancy in the world.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Health', 'Research'],
          },
          {
            id: 'pub-2',
            image: '/images/publication-ecowas-waka.jpg',
            title: 'Ecowas Waka - A Freer Border Initiative',
            description: 'Transform your ideas into stunning mobile applications that captivate and engage your target audience.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Policy', 'Freedom'],
          },
          {
            id: 'pub-3',
            image: '/images/publication-ownership.jpg',
            title: 'Our Ownership Culture - Property rights in Africa',
            description: 'Africans from various corners of the continent have always respected private property rights. However, there are unique challenges in the modern practice of property rights in Africa.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Economics', 'Rights'],
          },
          {
            id: 'pub-4',
            image: '/images/publication-missionary-schools.jpg',
            title: 'Nationalisation of Private Missionary Schools in Nigeria',
            description: 'Published by the George Ayittey Society, in it\'s review of African ........This paper traces the decline in the quality of education in Nigeria, to the Nationalisation of private missionary schools.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Education', 'Policy'],
          },
          {
            id: 'pub-5',
            image: '/images/publication-freedom.jpg',
            title: 'Are we not free?',
            description: 'The freedom struggle in Africa has come a long way since the abolition of slave trade. However, the the struggle for political independence and today, the frontiers of African freedom struggle, is mostly economic but there remains some human rights issues.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Freedom', 'Rights'],
          },
          {
            id: 'pub-6',
            image: '/images/publication-trade.jpg',
            title: 'Trade and Prosperity',
            description: 'In indigenous African thinking, trade and prosperity are inseparably linked. This report details the intricate linkages between trade and prosperity; the opportunities this presents for African development and the implications of neglecting African Continental Free Trade.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Economics', 'Trade'],
          },
        ],
      },
    },
    {
      id: 'featured-philosophy',
      type: 'featured-publication',
      title: 'Our African Philosophy',
      data: {
        featuredTitle: 'Philosophical roots for African Development',
        featuredSubtitle: 'A special report on Yoruba Classical Liberalism',
        description: 'Africa needs original thinking that amplifies indigenous voices and connects the vision for an African future, with ancestral roots. We believe that Yoruba Classical Liberalism offers all the deep insights needed to lay a solid foundation for African Development.',
        backgroundImage: '/images/african-philosophy-bg.jpg',
        downloadUrl: '/downloads/sample-publication.pdf',
      },
    },
    {
      id: 'four-groups',
      type: 'publications',
      title: 'The Four Groups',
      description: 'Explore our research papers, reports, and thought leadership publications',
      data: {
        publications: [
          {
            id: 'pub-1',
            image: '/images/publication-life-expectancy.jpg',
            title: 'Experienced Men',
            description: 'To run the program, to study and modify, to redistribute copies, and to distribute modified versions.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Health', 'Research'],
          },
          {
            id: 'pub-2',
            image: '/images/publication-ecowas-waka.jpg',
            title: 'Experienced Women',
            description: 'Africans from various corners of the continent have always respected private property rights. However, there are unique challenges in the modern practice of property rights in Africa.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Policy', 'Freedom'],
          },
          {
            id: 'pub-3',
            image: '/images/publication-ownership.jpg',
            title: 'Experienced Youth',
            description: 'The freedom struggle in Africa has come a long way since the abolition of slave trade. However, the the struggle for political independence and today, the frontiers of African freedom struggle, is mostly economic but there remains some human rights issues.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Economics', 'Rights'],
          },
          {
            id: 'pub-4',
            image: '/images/publication-missionary-schools.jpg',
            title: 'Experienced Foreigners',
            description: 'Published by the George Ayittey Society, in it\'s review of African ........This paper traces the decline in the quality of education in Nigeria, to the Nationalisation of private missionary schools.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Education', 'Policy'],
          },
        ],
      },
    },
    {
      id: 'programs',
      type: 'grid',
      title: 'Our Programs',
      description: 'Discover our comprehensive range of educational programs designed to inspire and empower',
      data: {
        items: [
          {
            id: 'program-1',
            image: '/images/program-undergraduate.jpg',
            title: 'Undergraduate Studies',
            description: 'Build a strong foundation with our comprehensive undergraduate programs across multiple disciplines.',
            href: '/programs/undergraduate',
            tags: ['4 Years', 'Full-time'],
          },
          {
            id: 'program-2',
            image: '/images/program-graduate.jpg',
            title: 'Graduate Programs',
            description: 'Advance your expertise with our specialized graduate programs and research opportunities.',
            href: '/programs/graduate',
            tags: ['2-3 Years', 'Research'],
          },
          {
            id: 'program-3',
            image: '/images/program-professional.jpg',
            title: 'Professional Development',
            description: 'Enhance your skills with our professional development courses and certification programs.',
            href: '/programs/professional',
            tags: ['Flexible', 'Online'],
          },
          {
            id: 'program-4',
            image: '/images/program-research.jpg',
            title: 'Research Initiatives',
            description: 'Participate in groundbreaking research projects that address real-world challenges.',
            href: '/programs/research',
            tags: ['Innovation', 'Collaboration'],
          },
          {
            id: 'program-5',
            image: '/images/program-summer.jpg',
            title: 'Summer Programs',
            description: 'Intensive summer courses and workshops for students looking to accelerate their learning.',
            href: '/programs/summer',
            tags: ['6-8 Weeks', 'Intensive'],
          },
          {
            id: 'program-6',
            image: '/images/program-exchange.jpg',
            title: 'Exchange Programs',
            description: 'Experience global education through our international exchange partnerships.',
            href: '/programs/exchange',
            tags: ['International', '1 Semester'],
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'about',
      type: 'text',
      title: 'About Chale Institute',
      data: {
        content: 'Founded with a vision to transform education, Chale Institute has been at the forefront of academic excellence and innovation for over two decades. Our commitment to fostering critical thinking, creativity, and leadership has helped thousands of students achieve their dreams and make meaningful contributions to society. We believe in a holistic approach to education that combines rigorous academics with practical experience, preparing our students not just for careers, but for life.',
        image: {
          src: '/images/about-campus.jpg',
          alt: 'Chale Institute Campus',
          position: 'right',
        },
        layout: 'split',
      },
    },
    {
      id: 'features',
      type: 'grid',
      title: 'Why Choose Chale Institute',
      description: 'Experience the advantages that set us apart',
      data: {
        items: [
          {
            id: 'feature-1',
            icon: '🎓',
            title: 'World-Class Faculty',
            description: 'Learn from renowned experts and industry leaders who are passionate about teaching and mentorship.',
            href: '/about/faculty',
          },
          {
            id: 'feature-2',
            icon: '🔬',
            title: 'State-of-the-Art Facilities',
            description: 'Access cutting-edge laboratories, libraries, and technology to support your learning journey.',
            href: '/campus/facilities',
          },
          {
            id: 'feature-3',
            icon: '🌍',
            title: 'Global Network',
            description: 'Connect with a diverse community of students, alumni, and partners from around the world.',
            href: '/community/network',
          },
          {
            id: 'feature-4',
            icon: '💼',
            title: 'Career Support',
            description: 'Benefit from comprehensive career services, internship opportunities, and industry connections.',
            href: '/services/career',
          },
          {
            id: 'feature-5',
            icon: '🏆',
            title: 'Excellence in Research',
            description: 'Contribute to impactful research that addresses global challenges and advances knowledge.',
            href: '/research',
          },
          {
            id: 'feature-6',
            icon: '🤝',
            title: 'Collaborative Environment',
            description: 'Thrive in a supportive community that encourages collaboration and interdisciplinary learning.',
            href: '/about/culture',
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'mission',
      type: 'text',
      title: 'Our Mission',
      data: {
        content: 'At Chale Institute, our mission is to cultivate intellectual curiosity, foster innovation, and develop leaders who will shape a better future. We are committed to providing an inclusive and supportive environment where every student can reach their full potential. Through excellence in teaching, groundbreaking research, and meaningful community engagement, we strive to make a positive impact on society and contribute to the advancement of knowledge across all disciplines.',
        layout: 'centered',
      },
    },
    {
      id: 'primacy-of-individual',
      type: 'featured-publication',
      title: 'The Primacy of the Individual',
      data: {
        featuredTitle: 'Ori, Chi and XYZ: Indigenous African',
        featuredSubtitle: 'Conceptions of Individualism',
        description: 'Individualism has often been portrayed as alien  to Africans. In this essay, we explore the indigenous African conceptions of Individualism and demonstrate unique African insights into the universal primacy of the individual, in any society.',
        backgroundImage: '/images/african-philosophy-bg.jpg',
        downloadUrl: '/downloads/sample-publication.pdf',
      },
    },
    {
      id: 'policy-briefs',
      type: 'publications',
      title: 'Policy Briefs',
      description: 'Explore our policy publications',
      data: {
        publications: [
          {
            id: 'pub-1',
            image: '/images/publication-life-expectancy.jpg',
            title: 'Ondo FTZ Policy Review',
            description: 'With the commencement of the long-awaited construction of the coastal road, directly linking Lekki Free Trade Zone in Lagos State, to Olokola Free Trade Zone in Ondo State, it is time for Ondo state government to take a clear position.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Health', 'Research'],
          },
          {
            id: 'pub-2',
            image: '/images/publication-ecowas-waka.jpg',
            title: 'The return of Mission Schools',
            description: 'The deterioration of mission schools in Nigeria over the last 5 decades since they were forcefully taken over by the military government, alongside the success stories of “returned” schools, makes a compelling case for the return of all misson schools in Nigeria. ',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Policy', 'Freedom'],
          },
          {
            id: 'pub-3',
            image: '/images/publication-ownership.jpg',
            title: 'City aesthetics and public health',
            description: 'Nigerian cities do not pass the stroller test, which means that on the average street, a mother cannot take walks with a baby in a stroller due to open sewers, garbage, street trading, indiscriminate car parking, lack of shade trees along the streets and lack of streetlights at night and general safety challenges. This has to change....',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Economics', 'Rights'],
          },
          {
            id: 'pub-4',
            image: '/images/publication-missionary-schools.jpg',
            title: 'Universal Basic Education',
            description: 'Published by the George Ayittey Society, in it\'s review of African ........This paper traces the decline in the quality of education in Nigeria, to the Nationalisation of private missionary schools.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Education', 'Policy'],
          },
          {
            id: 'pub-5',
            image: '/images/publication-freedom.jpg',
            title: 'The Alternative Medicine Policy',
            description: 'The freedom struggle in Africa has come a long way since the abolition of slave trade. However, the the struggle for political independence and today, the frontiers of African freedom struggle, is mostly economic but there remains some human rights issues.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Freedom', 'Rights'],
          },
          {
            id: 'pub-6',
            image: '/images/publication-trade.jpg',
            title: 'Minimum Wage in Nigeria: A review',
            description: 'In indigenous African thinking, trade and prosperity are inseparably linked. This report details the intricate linkages between trade and prosperity; the opportunities this presents for African development and the implications of neglecting African Continental Free Trade.',
            downloadUrl: '/downloads/sample-publication.pdf',
            tags: ['Economics', 'Trade'],
          },
        ],
      },
    },
    {
      id: 'market-solution',
      type: 'featured-publication',
      title: 'The Market Solution',
      data: {
        featuredTitle: 'The Economic Problem is best solved by the Market',
        featuredSubtitle: 'A special report on Yoruba Classical Liberalism',
        description: 'In traditional Africa, both historically and in contemporary times, the marketplace has always been the go-to, for solutions to all sorts of problem outside security and arbitration. People went to the kings for security and arbitration, and to the market for all other solutions.',
        backgroundImage: '/images/african-philosophy-bg.jpg',
        downloadUrl: '/downloads/sample-publication.pdf',
      },
    },
    {
      id: 'testimonials',
      type: 'grid',
      title: 'Student Success Stories',
      description: 'Hear from our students and alumni about their experiences',
      data: {
        items: [
          {
            id: 'testimonial-1',
            image: '/images/student-1.jpg',
            title: 'Sarah Johnson',
            description: '"Chale Institute provided me with the knowledge, skills, and confidence to pursue my dream career in biotechnology. The faculty support and research opportunities were exceptional."',
            tags: ['Class of 2023', 'Biotechnology'],
          },
          {
            id: 'testimonial-2',
            image: '/images/student-2.jpg',
            title: 'Michael Chen',
            description: '"The collaborative environment and diverse perspectives at Chale Institute helped me grow both academically and personally. I made lifelong connections here."',
            tags: ['Class of 2022', 'Computer Science'],
          },
          {
            id: 'testimonial-3',
            image: '/images/student-3.jpg',
            title: 'Aisha Patel',
            description: '"The exchange program opened my eyes to different cultures and approaches to problem-solving. It was a transformative experience that shaped my worldview."',
            tags: ['Class of 2024', 'International Studies'],
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'news-events',
      type: 'grid',
      title: 'Latest News & Events',
      description: 'Stay updated with the latest happenings at Chale Institute',
      data: {
        items: [
          {
            id: 'news-1',
            image: '/images/news-1.jpg',
            title: 'Annual Research Symposium 2024',
            description: 'Join us for our flagship research event showcasing groundbreaking projects from students and faculty across all departments.',
            href: '/news/research-symposium-2024',
            tags: ['March 15-17', 'Research'],
          },
          {
            id: 'news-2',
            image: '/images/news-2.jpg',
            title: 'New Innovation Lab Opening',
            description: 'State-of-the-art innovation lab equipped with cutting-edge technology opens its doors to students this semester.',
            href: '/news/innovation-lab-opening',
            tags: ['Campus News', 'Facilities'],
          },
          {
            id: 'news-3',
            image: '/images/news-3.jpg',
            title: 'International Partnership Announced',
            description: 'Chale Institute partners with leading universities worldwide to expand global learning opportunities for students.',
            href: '/news/international-partnership',
            tags: ['Global', 'Partnership'],
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'academic-departments',
      type: 'grid',
      title: 'Academic Departments',
      description: 'Explore our diverse range of academic disciplines',
      data: {
        items: [
          {
            id: 'dept-1',
            icon: '💻',
            title: 'Computer Science & Engineering',
            description: 'Cutting-edge programs in software development, AI, machine learning, and cybersecurity.',
            href: '/departments/computer-science',
          },
          {
            id: 'dept-2',
            icon: '🧬',
            title: 'Life Sciences & Biotechnology',
            description: 'Advanced research and education in biology, genetics, and biomedical sciences.',
            href: '/departments/life-sciences',
          },
          {
            id: 'dept-3',
            icon: '⚗️',
            title: 'Chemistry & Materials Science',
            description: 'Innovative programs exploring chemical processes and advanced materials.',
            href: '/departments/chemistry',
          },
          {
            id: 'dept-4',
            icon: '📊',
            title: 'Business & Economics',
            description: 'Comprehensive business education with focus on entrepreneurship and global markets.',
            href: '/departments/business',
          },
          {
            id: 'dept-5',
            icon: '🎨',
            title: 'Arts & Humanities',
            description: 'Rich programs in literature, history, philosophy, and creative arts.',
            href: '/departments/arts-humanities',
          },
          {
            id: 'dept-6',
            icon: '🔧',
            title: 'Engineering & Technology',
            description: 'Hands-on engineering programs in mechanical, electrical, and civil engineering.',
            href: '/departments/engineering',
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'campus-life',
      type: 'text',
      title: 'Vibrant Campus Life',
      data: {
        content: 'Life at Chale Institute extends far beyond the classroom. Our vibrant campus community offers countless opportunities for personal growth, social connection, and cultural enrichment. From student clubs and organizations to sports teams and cultural events, there\'s something for everyone. Our modern facilities include recreational centers, performance spaces, and collaborative study areas designed to support your holistic development. Join a community where lifelong friendships are formed and memories are made.',
        image: {
          src: '/images/campus-life.jpg',
          alt: 'Students enjoying campus life',
          position: 'left',
        },
        layout: 'split',
      },
    },
    {
      id: 'student-resources',
      type: 'grid',
      title: 'Student Resources & Support',
      description: 'Comprehensive services to support your academic journey',
      data: {
        items: [
          {
            id: 'resource-1',
            icon: '📚',
            title: 'Library & Learning Commons',
            description: 'Access extensive digital and physical collections, study spaces, and research support services.',
            href: '/resources/library',
          },
          {
            id: 'resource-2',
            icon: '🏥',
            title: 'Health & Wellness Center',
            description: 'Comprehensive health services, counseling, and wellness programs for student wellbeing.',
            href: '/resources/health-wellness',
          },
          {
            id: 'resource-3',
            icon: '🎯',
            title: 'Academic Advising',
            description: 'Personalized guidance to help you navigate your academic path and achieve your goals.',
            href: '/resources/advising',
          },
          {
            id: 'resource-4',
            icon: '💰',
            title: 'Financial Aid & Scholarships',
            description: 'Explore funding opportunities and financial support to make education accessible.',
            href: '/resources/financial-aid',
          },
          {
            id: 'resource-5',
            icon: '🌐',
            title: 'International Student Services',
            description: 'Dedicated support for international students including visa assistance and cultural integration.',
            href: '/resources/international',
          },
          {
            id: 'resource-6',
            icon: '♿',
            title: 'Accessibility Services',
            description: 'Ensuring equal access and accommodation for students with diverse needs.',
            href: '/resources/accessibility',
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'research-impact',
      type: 'text',
      title: 'Research That Makes a Difference',
      data: {
        content: 'At Chale Institute, research is at the heart of everything we do. Our faculty and students are engaged in cutting-edge research that addresses some of the world\'s most pressing challenges. From developing sustainable technologies to advancing medical breakthroughs, our research has real-world impact. We provide state-of-the-art facilities, funding opportunities, and collaborative partnerships that enable groundbreaking discoveries. Join us in pushing the boundaries of knowledge and creating solutions for a better tomorrow.',
        layout: 'centered',
      },
    },
    {
      id: 'alumni-network',
      type: 'grid',
      title: 'Join Our Global Alumni Network',
      description: 'Connect with over 50,000 alumni making an impact worldwide',
      data: {
        items: [
          {
            id: 'alumni-1',
            image: '/images/alumni-1.jpg',
            title: 'Dr. James Martinez',
            description: 'Leading researcher in renewable energy, pioneering solar technology innovations that are transforming the industry.',
            tags: ['Class of 2015', 'Energy'],
          },
          {
            id: 'alumni-2',
            image: '/images/alumni-2.jpg',
            title: 'Lisa Thompson',
            description: 'CEO of a successful tech startup, creating AI solutions that improve healthcare accessibility globally.',
            tags: ['Class of 2018', 'Technology'],
          },
          {
            id: 'alumni-3',
            image: '/images/alumni-3.jpg',
            title: 'Dr. Raj Patel',
            description: 'Award-winning educator and author, developing innovative teaching methods adopted by schools worldwide.',
            tags: ['Class of 2012', 'Education'],
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    // {
    //   id: 'cta-apply',
    //   type: 'cta',
    //   data: {
    //     title: 'Ready to Start Your Journey?',
    //     description: 'Join our community of learners, innovators, and leaders. Applications are now open for the upcoming academic year.',
    //     primaryButton: {
    //       label: 'Apply Now',
    //       href: '/apply',
    //       variant: 'primary',
    //     },
    //     secondaryButton: {
    //       label: 'Schedule a Visit',
    //       href: '/visit',
    //       variant: 'secondary',
    //     },
    //   },
    // },
  ],
};
