import { PageContent } from './types';

export const programsContent: PageContent = {
  metadata: {
    title: 'Programs - Chale Institute',
    description: 'Explore our comprehensive range of educational programs designed to inspire and empower students.',
    keywords: ['programs', 'education', 'courses', 'degrees', 'learning'],
    ogImage: '/images/og-image.jpg',
  },
  hero: {
    title: 'Our Educational Programs',
    subtitle: 'Discover our comprehensive range of programs designed to inspire, challenge, and empower the next generation of leaders and innovators.',
    backgroundImage: '/images/program-undergraduate.jpg',
    cta: {
      title: '',
      primaryButton: {
        label: 'Explore Programs',
        href: '#program-types',
      },
    },
  },
  sections: [
    {
      id: 'program-types',
      type: 'grid',
      title: 'Program Types',
      description: 'Choose the program that fits your goals and aspirations',
      data: {
        items: [
          {
            id: 'prog-1',
            image: '/images/program-undergraduate.jpg',
            title: 'Undergraduate Programs',
            description: 'Build a strong foundation with our comprehensive 4-year undergraduate programs across multiple disciplines including sciences, humanities, engineering, and business.',
            href: '/programs/undergraduate',
            tags: ['4 Years', 'Full-time'],
          },
          {
            id: 'prog-2',
            image: '/images/program-graduate.jpg',
            title: 'Graduate Programs',
            description: 'Advance your expertise with our specialized 2-3 year graduate programs featuring research opportunities and industry partnerships.',
            href: '/programs/graduate',
            tags: ['2-3 Years', 'Research'],
          },
          {
            id: 'prog-3',
            image: '/images/program-professional.jpg',
            title: 'Professional Development',
            description: 'Enhance your skills with flexible professional development courses and certification programs designed for working professionals.',
            href: '/programs/professional',
            tags: ['Flexible', 'Online'],
          },
          {
            id: 'prog-4',
            image: '/images/program-research.jpg',
            title: 'Research Initiatives',
            description: 'Participate in groundbreaking research projects that address real-world challenges and contribute to advancing knowledge.',
            href: '/programs/research',
            tags: ['Innovation', 'Collaboration'],
          },
          {
            id: 'prog-5',
            image: '/images/program-summer.jpg',
            title: 'Summer Programs',
            description: 'Intensive 6-8 week summer courses and workshops for students looking to accelerate their learning and explore new subjects.',
            href: '/programs/summer',
            tags: ['6-8 Weeks', 'Intensive'],
          },
          {
            id: 'prog-6',
            image: '/images/program-exchange.jpg',
            title: 'Exchange Programs',
            description: 'Experience global education through our international exchange partnerships with leading universities worldwide.',
            href: '/programs/exchange',
            tags: ['International', '1 Semester'],
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'academic-departments',
      type: 'grid',
      title: 'Academic Departments',
      description: 'Explore our diverse range of academic disciplines',
      data: {
        items: [
          {
            id: 'dept-1',
            icon: '💻',
            title: 'Computer Science & Engineering',
            description: 'Cutting-edge programs in software development, AI, machine learning, and cybersecurity.',
            href: '/departments/computer-science',
          },
          {
            id: 'dept-2',
            icon: '🧬',
            title: 'Life Sciences & Biotechnology',
            description: 'Advanced research and education in biology, genetics, and biomedical sciences.',
            href: '/departments/life-sciences',
          },
          {
            id: 'dept-3',
            icon: '⚗️',
            title: 'Chemistry & Materials Science',
            description: 'Innovative programs exploring chemical processes and advanced materials.',
            href: '/departments/chemistry',
          },
          {
            id: 'dept-4',
            icon: '📊',
            title: 'Business & Economics',
            description: 'Comprehensive business education with focus on entrepreneurship and global markets.',
            href: '/departments/business',
          },
          {
            id: 'dept-5',
            icon: '🎨',
            title: 'Arts & Humanities',
            description: 'Rich programs in literature, history, philosophy, and creative arts.',
            href: '/departments/arts-humanities',
          },
          {
            id: 'dept-6',
            icon: '🔧',
            title: 'Engineering & Technology',
            description: 'Hands-on engineering programs in mechanical, electrical, and civil engineering.',
            href: '/departments/engineering',
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'program-features',
      type: 'grid',
      title: 'What Makes Our Programs Special',
      description: 'Key features that set our programs apart',
      data: {
        items: [
          {
            id: 'feat-1',
            icon: '👨‍🏫',
            title: 'Expert Faculty',
            description: 'Learn from renowned scholars and industry experts who are leaders in their fields.',
            href: '/about/faculty',
          },
          {
            id: 'feat-2',
            icon: '🔬',
            title: 'Research Opportunities',
            description: 'Engage in cutting-edge research projects from day one of your studies.',
            href: '/research',
          },
          {
            id: 'feat-3',
            icon: '🌍',
            title: 'Global Perspective',
            description: 'Study with international peers and participate in global learning experiences.',
            href: '/programs/exchange',
          },
          {
            id: 'feat-4',
            icon: '💼',
            title: 'Career Preparation',
            description: 'Comprehensive career services, internships, and industry partnerships.',
            href: '/services/career',
          },
          {
            id: 'feat-5',
            icon: '🏆',
            title: 'Hands-On Learning',
            description: 'Project-based learning and practical experience in real-world settings.',
            href: '/programs',
          },
          {
            id: 'feat-6',
            icon: '🤝',
            title: 'Collaborative Community',
            description: 'Work alongside peers in a supportive and inclusive learning environment.',
            href: '/community',
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'program-overview',
      type: 'text',
      title: 'Program Overview',
      data: {
        content: 'At Chale Institute, we offer a diverse portfolio of programs designed to meet the needs of students at every stage of their academic journey. Whether you\'re beginning your undergraduate studies, pursuing advanced research, or seeking professional development, we have a program tailored to your goals. Our programs combine rigorous academics with practical experience, ensuring you graduate with both knowledge and skills. We emphasize critical thinking, creativity, and leadership development, preparing our students to make meaningful contributions to their fields and communities.',
        layout: 'centered',
      },
    },
    {
      id: 'admission-requirements',
      type: 'grid',
      title: 'Program Requirements',
      description: 'What you need to know about each program level',
      data: {
        items: [
          {
            id: 'req-1',
            icon: '🎓',
            title: 'Undergraduate Entry',
            description: 'High school diploma, standardized test scores, transcripts, and application essays required.',
            href: '/admissions',
          },
          {
            id: 'req-2',
            icon: '📚',
            title: 'Graduate Entry',
            description: 'Bachelor\'s degree, GRE/GMAT scores, statement of purpose, and professional references.',
            href: '/admissions',
          },
          {
            id: 'req-3',
            icon: '💼',
            title: 'Professional Entry',
            description: 'Relevant work experience and program-specific prerequisites. Flexible admission criteria.',
            href: '/admissions',
          },
          {
            id: 'req-4',
            icon: '🌐',
            title: 'International Students',
            description: 'English proficiency test, visa support, and additional documentation required.',
            href: '/admissions',
          },
          {
            id: 'req-5',
            icon: '⏰',
            title: 'Application Timeline',
            description: 'Early applications recommended. Rolling admissions for most programs.',
            href: '/admissions',
          },
          {
            id: 'req-6',
            icon: '💰',
            title: 'Financial Aid',
            description: 'Scholarships, grants, and loans available. FAFSA completion recommended.',
            href: '/admissions',
          },
        ],
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
        },
      },
    },
    {
      id: 'programs-cta',
      type: 'cta',
      data: {
        title: 'Ready to Start Your Journey?',
        description: 'Explore our programs and find the perfect fit for your academic and career goals.',
        primaryButton: {
          label: 'Apply Now',
          href: '/admissions',
          variant: 'primary',
        },
        secondaryButton: {
          label: 'Learn More',
          href: '#program-types',
          variant: 'outline',
        },
      },
    },
  ],
};
